services:
  portfolio:
    image: golang:1.24.2
    container_name: portifolio
    restart: always 
    ports:
      - 2053:2053 
  portdb:
    image: redis:6.2-alpine
    container_name: portdb
    restart: always
    ports:
      - 6378:6379
    env_file: .env
    volumes:
      - ./redis-data:/data
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
