networks:
  go-portifolio-network:

services:
  portifolio:
    build: 
      context: .
    container_name: portifolio
    restart: always
    ports:
      - 2053:2053
    depends_on:
      - portdb
    networks:
      - go-portifolio-network
  portdb:
    image: redis:6.2-alpine
    container_name: portdb
    restart: always
    ports:
      - 6378:6379
    env_file: .env.prod
    volumes:
      - ./redis-data:/data
    networks:
      - go-portifolio-network
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
