services:
  portdb:
    image: redis:6.2-alpine
    container_name: portdb
    restart: always
    ports:
      - 6379:6379
    env_file: .env
    volumes:
      - ./redis-data:/data
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
